### PR TITLE
fix: change referrer media type to oci image manifest

### LINKED ISSUE #24: Referrer media type is invalid
I'm attempting to push a trivy scan as Sarif format as a referrer attached to my image. From the referrer artifact's manifest, I see that the media type is set to the value of the referenced artifact (subject).
```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/sarif+json",
    "size": 233,
    "digest": "sha256:4cb6c827a0a5603f6d16499e753f72f8a5bf1b391e23f84aebf8bf8402487221"
  },
  "layers": [
    {
      "mediaType": "application/sarif+json",
      "size": 15633,
      "digest": "sha256:512f005dac928539c8ad49f007ef329a959fd959fece98a238fa3fed3ae82ccc"
    }
  ],
  "annotations": {
    "created-by": "trivy",
    "org.opencontainers.artifact.created": "2023-10-11T20:12:01Z",
    "org.opencontainers.artifact.description": "SARIF"
  },
  "subject": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 737,
    "digest": "sha256:c419f6f2cf62261525ee07c031044ead50086fc94a5edd482f6d469b67ba1292"
  }
}
```
Here you can see the media type is set to `application/vnd.docker.distribution.manifest.v2+json`. However, only OCI image manifest has support for the new subject field. The issue stems from this line here:
https://github.com/aquasecurity/trivy-plugin-referrer/blob/d1f2e4bb41bff0b8e52868198db138383e420297/put.go#L55C30-L55C40

I think the mediatype should be set to be `application/vnd.oci.image.manifest.v1+json`

### PR DESCRIPTION
**Pull request by akashsinghal**
fixes #24

### CODE REVIEW

**Comment by knqyf263** [comment]
@otms61 Can you please take a look?

**Comment by otms61** [comment]
Thank you for your detailed issue and PR! We appreciate the time you've taken to review the specification and the code!

You are correct that the media type of the referrer should ideally conform to the `application/vnd.oci.image.manifest.v1+json` to utilize the subject field properly. However, this causes a problem specifically with DockerHub, which doesn't yet support this media type. We cannot push a referrer to DockerHub if we change all media types to `application/vnd.oci.image.manifest.v1+json`.  Given the large number of users of DockerHub, we would prefer to keep the current implementation.

<details><summary>Details</summary>
<p>

Current implementations can write to DockerHub.
```
> git branch --show-current
main

> go build .

> trivy image --format sarif  otms61/my-alpine-2 | ./trivy-plugin-referrer put
2023-10-13T14:17:16.181+0900	INFO	Vulnerability scanning is enabled
2023-10-13T14:17:16.181+0900	INFO	Secret scanning is enabled
2023-10-13T14:17:16.181+0900	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-10-13T14:17:16.181+0900	INFO	Please see also https://aquasecurity.github.io/trivy/v0.44/docs/scanner/secret/#recommendation for faster secret detection
2023-10-13T14:17:16.192+0900	INFO	Detected OS: alpine
2023-10-13T14:17:16.192+0900	INFO	Detecting Alpine vulnerabilities...
2023-10-13T14:17:16.193+0900	INFO	Number of language-specific files: 0
2023-10-13T14:17:16.200+0900	INFO	Failed to detect a valid SBOM: ensure the provided SBOM is generated by Trivy, as only Trivy-generated SBOMs are currently supported
2023-10-13T14:17:16.201+0900	INFO	SARIF detected
2023-10-13T14:17:17.681+0900	INFO	Pushing referrer to index.docker.io/otms61/my-alpine-2@sha256:c68a701624b485bc1da7b4c8a16aa15a4e32eddd07b6245b21cae86eb7b6889d
```

Implementations using application/vnd.oci.image.manifest.v1+json cannot write to DockerHub.
```
> git branch --show-current
fix-mediatype

> go build .

> trivy image --format sarif  otms61/my-alpine-2 | ./trivy-plugin-referrer put
2023-10-13T14:18:05.880+0900	INFO	Vulnerability scanning is enabled
2023-10-13T14:18:05.880+0900	INFO	Secret scanning is enabled
2023-10-13T14:18:05.880+0900	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-10-13T14:18:05.880+0900	INFO	Please see also https://aquasecurity.github.io/trivy/v0.44/docs/scanner/secret/#recommendation for faster secret detection
2023-10-13T14:18:05.898+0900	INFO	Detected OS: alpine
2023-10-13T14:18:05.898+0900	INFO	Detecting Alpine vulnerabilities...
2023-10-13T14:18:05.899+0900	INFO	Number of language-specific files: 0
2023-10-13T14:18:05.907+0900	INFO	Failed to detect a valid SBOM: ensure the provided SBOM is generated by Trivy, as only Trivy-generated SBOMs are currently supported
2023-10-13T14:18:05.908+0900	INFO	SARIF detected
2023-10-13T14:18:07.319+0900	INFO	Pushing referrer to index.docker.io/otms61/my-alpine-2@sha256:a95f7bd95d46ec35007a71314c2ac16504ad4ff33e92b4e85e78137308cd1f28
Error: error putting referrer: error pushing referrer: PUT https://index.docker.io/v2/otms61/my-alpine-2/manifests/sha256:a95f7bd95d46ec35007a71314c2ac16504ad4ff33e92b4e85e78137308cd1f28: NOTFOUND: not found
Usage:
   put [flags]

Examples:
  trivy image -q -f cyclonedx YOUR_IMAGE | trivy referrer put
  # Put SBOM attestation
  trivy referrer put -f sbom.json

Flags:
      --annotation strings   annotations associated with the artifact (can specify multiple or separate values with commas: key1=path1,key2=path2)
  -f, --file string          file path. If a file path is not specified, it will accept input from the standard input.
  -h, --help                 help for put
      --subject string       set the subject to a reference (If the value is not set, it will attempt to detect it automatically from the input)

Global Flags:
  -d, --debug      debug mode
      --insecure   allow insecure server connections
  -q, --quiet      suppress log output

2023-10-13T14:18:09.494+0900	FATAL	error putting referrer: error pushing referrer: PUT https://index.docker.io/v2/otms61/my-alpine-2/manifests/sha256:a95f7bd95d46ec35007a71314c2ac16504ad4ff33e92b4e85e78137308cd1f28: NOTFOUND: not found
```

</p>
</details> 

Another implementation approach would be to register the referrer without writing the subject in the manifest when the OCI registry is DockerHub, but this isn't easy. The `remote.Write` function, which is used to write a referrer, determines whether to write the referrer based on the presence of the subject field in the manifest([ref](https://github.com/otms61/go-containerregistry/blob/ed5c185df4199b81bb5635e483ebfbc1b73d17f8/pkg/v1/remote/write.go#L771-L789)), so a customized implementation is required to change it.

For these reasons, we are leaning towards maintaining the current implementation despite its discrepancy with the ideal specification. If you have any alternative solutions or ideas, we would be happy to hear them.

**Comment by akashsinghal** [comment]
Thanks for the explanation @otms61. That totally makes sense. We've been testing with Azure Container Registry which is OCI 1.1 spec compliant which is why we were seeing issues. Other registries adopting this will likely face similar issues. Would conditionally setting the media type based on the registry login host being dockerhub work? This would require parsing the `Subject` `putOption` in the [`putReferrers` function](https://github.com/aquasecurity/trivy-plugin-referrer/blob/d1f2e4bb41bff0b8e52868198db138383e420297/put.go#L87) and altering the `referrer.Image()` function to take in a media type to set on the `Image` instead.  I recognize it would require special casing for dockerhub explicitly in the code. 

If you are more comfortable keeping the current implementation, I understand. This is not blocking us. We can recommend other tools such as `oras attach` command to take the file output from `trivy` to push to ACR.

**Comment by otms61** [comment]
@akashsinghal  Thank you for your explanation!

I assumed that the referrer generated for an Image with `application/vnd.oci.image.manifest.v1+json` would use the same media type and therefore not cause any problems for the OCI 1.1 regsitry. It seems that I am missing something.

Can you tell us the situation when the problem occurred? Also, is it possible for me to reproduce the issue? In particular, I would like to know the media type of the scanned image's manifest.

I may be mistaken, but looking at [the ACR features](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-image-formats), it seems that the Docker Image manifest is supported. For an image with the docker image manifest, is the referrer media type expected to be set to `application/vnd.oci.image.manifest.v1+json`?

**Comment by akashsinghal** [comment]
> I assumed that the referrer generated for an Image with application/vnd.oci.image.manifest.v1+json would use the same media type and therefore not cause any problems for the OCI 1.1 regsitry. It seems that I am missing something.

Yes, if the subject's media type is already an OCI manifest, then the media type of the referrer manifest will also be OCI manifest media type which is expected and OCI 1.1 compliant. 

> Can you tell us the situation when the problem occurred? Also, is it possible for me to reproduce the issue? In particular, I would like to know the media type of the scanned image's manifest.

This problem is specific to when you attempt to attach the trivy report referrer to a docker image (mediatype=`application/vnd.docker.distribution.manifest.v2+json`). Since the media type of the referrer manifest is set to be same as the subject manifest, the referrer will be treated as a docker manifest. You can reproduce this issue by pulling any docker manifest and then pushing it to an ACR. Then attempt to use trivy to put the outputted report on the ACR subject. This will succeed however if you attempt to get the referrers (go though azure portal or run `oras discover`) you won't see the newly pushed referrer attached.

> For an image with the docker image manifest, is the referrer media type expected to be set to application/vnd.oci.image.manifest.v1+json?
Yes for all other registries other than dockerhub, the referrer media type is expected to be either `application/vnd.oci.image.manifest.v1+json` or `application/vnd.oci.image.index.v1+json`. This is because the OCI image spec only defines the optional `subject` field in the OCI image manifest or OCI image index manifest. As far as I know, there's no published docker manifest definition that contains the `subject` field. 

Thanks to your testing steps above, I was able to use them to note the dockerhub behavior. Dockerhub allows docker manifest with a `subject` field to be pushed but it will NOT allow OCI image manifests with a `subject` field. This is very unique to dockerhub. My guess is that this unique behavior is a temporary workaround so clients can use dockerhub for referrers in with tag-based fallback support. Dockerhub does not support the new `/referrers` API for returning the list of referrer's for a subject. Instead, client such as CRANE or ORAS must rely on the image index being pushed with a subject's referrer manifest digests.

Now, registries that are 1.1 compliant do have the `/referrers` api implementation. This means clients will NOT use the fallback (index) approach. For these registries (like ACR), the docker manifest with the `subject` field is NOT a valid referrer and thus the API response will not contain it. This is the crux of the issue here as the current implementation sets to the subject's media type. ACR does support docker manifest but it does NOT support docker manifests with a `subject` field as a referrer. (you can push the manifest but it won't be treated as a referrer). 

Hope this helps clear up the issue. Apologies for the confusion.

**Comment by otms61** [comment]
@akashsinghal Thank you for the detailed explanation! I apologize for the delayed response.

We are planning to proceed with the following approach:

We intend to merge this PR. Firstly, we are thinking of initially registering it using the `application/vnd.oci.image.manifest.v1+json` media type, which formally supports the subject. As an additional task, if registration fails on an OCI repository that can't save the `application/vnd.oci.image.manifest.v1+json` media type like DockerHub, we are considering implementing a fallback mechanism to write using the same media type we received. 
After implementing this, we plan to release it with a new version of the plugin.

Regarding the additional work, we're planning to take care of it on our end, but if you'd like to implement it, we can leave it to you. What would you like to do?

**Comment by akashsinghal** [comment]
@otms61 that would work great if the fallback implementation logic is added. If it's easier for you, I can just close my PR and wait for your team to make the full change + released version. If you'd like to merge this change and then build on top of it that's also fine. I appreciate your effort to help resolve this. I look forward to trying it out with the new support. Thanks!

**Comment by knqyf263** [comment]
@akashsinghal Thanks for your contribution!
@otms61 opened a subsequent PR as discussed above.
https://github.com/aquasecurity/trivy-plugin-referrer/pull/26

**Pull request merged**
